### PR TITLE
MVV - Minimal Viable Vagrantfile

### PR DESCRIPTION
**Pull request by jalessio**
@migurski here's a proposal for #546 

I know there's a lot of stuff in the air right now, so feel free to close this out if it's not time for this.

### CODE REVIEW

**Comment by migurski** [comment]
Nice, thanks. Can I add you to the writers for this repo, so this can be a branch here? That way, we'll be able to test and document the vagrant setup prior to merge, so it lands with appropriate updates in `docs/install.md`.

**Comment by jalessio** [comment]
Yep - happy to move the branch over if I have write access on the repo.

**Comment by migurski** [comment]
I have invited you to a team on this repo!

**Comment by migurski** [comment]
Any thoughts on debugging this? I see this output when I try `vagrant up --provider=VirtualBox`:

```
No usable default provider could be found for your system.

Vagrant relies on interactions with 3rd party systems, known as
"providers", to provide Vagrant with resources to run development
environments. Examples are VirtualBox, VMware, Hyper-V.

The easiest solution to this message is to install VirtualBox, which
is available for free on all major platforms.

If you believe you already have a provider available, make sure it
is properly installed and configured. You can see more details about
why a particular provider isn't working by forcing usage with
`vagrant up --provider=PROVIDER`, which should give you a more specific
error message for that particular provider.
```

I have VirtualBox 5.0.32, which is [in the list of supported versions](https://www.vagrantup.com/docs/virtualbox/). I'm not seeing any additional details about why this provider is not working despite using the `--provider` flag above. Where does Vagrant look when it’s trying to find VirtualBox?

**Comment by jalessio** [comment]
@migurski I've never had that issue before - Vagrant has always found VirtualBox for me (Mac, Windows, and Linux). Here's a known-working configuration on my current machine:

Host OS: OS X El Capitan 10.11.6
VirtualBox: 5.0.26
Vagrant: 1.9.0

The `--provider=VirtualBox` bit shouldn't even be needed since VirtualBox is the default provider.  I _think_ [Vagrant just shells out to to `VBoxManage`](https://github.com/mitchellh/vagrant/search?utf8=%E2%9C%93&q=VBoxManage) so maybe confirm that `VBoxManage` is in your `PATH`?

Here's where it lives on my machine:
```
> which VBoxManage
/usr/local/bin/VBoxManage
```
> VBoxManage --version
5.0.26r108824
```

FWIW, I installed both Vagrant and VirtualBox via [Homebrew Cask](https://caskroom.github.io/):
```
> brew cask install vagrant
> brew cask install virtualbox
```

**Comment by migurski** [comment]
That was it, thanks! I installed VirtualBox by downloading the .dmg, so I needed to add `/Applications/VirtualBox.app/Contents/MacOS` to my path.

**Comment by migurski** [comment]
So this basically works, yay. One of the tests, `TestOA.test_single_fr_lareunion`, fails for what I think are filesystem encoding reasons. I will try to figure out why that is. To get this merged, I think I'd like to replace the install docs introduction with Vagrant instructions.

**Comment by migurski** [comment]
Found and fixed the problem with La Réunion: https://github.com/openaddresses/machine/commit/681373e6f

**Comment by jalessio** [comment]
Superseded by #559

**Pull request closed without merging**
