### PR TITLE
Move mounted vagrant folder from /vagrant to /home/vagrant/machine

### PR DESCRIPTION
**Pull request by jalessio**
Follow-on to PR #559 based on feedback from @trescube:
* added `.vagrant` directory to `.gitignore` since this should never get checked in
* mount host directory into guest at `/home/vagrant/machine` so it's clearer that there's a relationship between the files on your development are the same files inside the VM
* update docs to reflect new directory name
* I hate trailing whitespace... my editor cleaned up a bunch of it (I can undo those changes if that's annoying)

I ran through this on a fresh VM without any issues.

### CODE REVIEW

**Comment by trescube** [comment]
Testing this now.  Is `vagrant destroy` the correct way to un-provision a vagrant machine?

**Comment by trescube** [comment]
Works great!

**Comment by jalessio** [comment]
@trescube yes, `vagrant destroy` will remove the VM entirely. It's equivalent from using the VirtualBox GUI to delete a VM.

Here are a few other useful commands:

```
vagrant up
```
Does 1 of 2 things:
* if the VM does not exist it will create it and then run whatever "provisioning" is configured (in our case it's a shell script that runs Chef)
* if the VM exists, but is stopped it will start the VM (but not run provisioning again)

```
vagrant provision
```
Will run the "provisioning" scripts on a VM that is already "up" (good for iterating on writing new Chef cookbooks, for example)

```
vagrant reload
```
reboots the VM

```
vagrant destroy
```
destroys/deletes the VM

**Comment by trescube** [comment]
Excellent, thanks!

**Comment by migurski** [comment]
I have no preferences on trailing whitespace, though it is annoying to see automated cleanup in files unrelated to a given change. In this case it's fine since you're actually proposing changes to the file in question!

**Pull request merged**
