### PR TITLE
Add verify_ssl flag that disables SSL cert verification when set to false

### PR DESCRIPTION
**Pull request by kreed**
We need this to get us-tx-san_antonio working since the certificates the website is serving are still broken.

### CODE REVIEW

**Comment by migurski** [comment]
Can we modify this slightly? My preference would be to not further burden the source file format (yet), and instead to set `verify_ssl=False` ifff a first try with `verify_ssl=True` fails.

**Comment by kreed** [comment]
Sure, I can do that. It would remove any security benefit from sources with working SSL though.

**Comment by migurski** [comment]
Yeah—I’m thinking that it becomes part of the output log, e.g. "we were able to fetch this via SSL" vs. "insecure download".

**Comment by kreed** [comment]
OK, I've got it logging to _L.warning. Will that end up in the output log?

**Comment by migurski** [comment]
Yes, that should do it.

**Pull request merged**
