### PR TITLE
Skip an ESRI feature with no geometry

### PR DESCRIPTION
**Pull request by iandees**
See https://github.com/openaddresses/openaddresses/commit/719c76502126ce1bfcb9341ce08ef5db8f770b6a

### CODE REVIEW

**Comment by migurski** [comment]
Is there a test you could add for this?

**Comment by iandees** [comment]
Yep, ran out of time. Just need to save [this entry](http://gis2.co.dakota.mn.us/arcgis/rest/services/DCGIS_OL_PropertyInformation/MapServer/3/1?f=json) as a fixture and run it through the existing tests.

**Comment by iandees** [comment]
Ok, I think this is ready now.

**Comment by migurski** [comment]
(I rebased when I merged)

**Pull request closed without merging**
