### PR TITLE
Use multipart s3 upload

### LINKED ISSUE #350: Implement ranged S3 upload for very large files
We are seeing failures in collection uploads, seemingly due to the issue described in https://github.com/boto/boto/issues/2207. @iandees suggests this approach: http://codeinpython.blogspot.de/2015/08/s3-upload-large-files-to-amazon-using.html

A sample traceback:

```
Traceback (most recent call last):
  File "/usr/local/bin/openaddr-collect-extracts", line 9, in <module>
    load_entry_point('OpenAddresses-Machine==2.21.5', 'console_scripts', 'openaddr-collect-extracts')()
  File "/usr/local/lib/python2.7/dist-packages/openaddr/ci/__init__.py", line 932, in decorated_function
    return route_function(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/openaddr/ci/collect.py", line 97, in main
    collection.publish(db)
  File "/usr/local/lib/python2.7/dist-packages/openaddr/ci/collect.py", line 184, in publish
    zip_key.set_contents_from_filename(self.zip.filename, **zip_args)
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/key.py", line 1362, in set_contents_from_filename
    encrypt_key=encrypt_key)
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/key.py", line 1293, in set_contents_from_file
    chunked_transfer=chunked_transfer, size=size)
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/key.py", line 750, in send_file
    chunked_transfer=chunked_transfer, size=size)
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/key.py", line 951, in _send_file_internal
    query_args=query_args
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/connection.py", line 668, in make_request
    retry_handler=retry_handler
  File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1071, in make_request
    retry_handler=retry_handler)
  File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1030, in _mexe
    raise ex
socket.error: [Errno 104] Connection reset by peer
```

### PR DESCRIPTION
**Pull request by iandees**
Fixes #350

Uses multipart S3 upload inspired by [this post](http://codeinpython.blogspot.de/2015/08/s3-upload-large-files-to-amazon-using.html) and kinda copied from [this gist](https://gist.github.com/fabiant7t/924094).

### CODE REVIEW

**Comment by iandees** [comment]
I need to think about how to add tests to this new code I wrote.

**Comment by migurski** [comment]
Would you like me to pick up this PR? Right now, new collection uploads are blocked on this. I’d like to remove the use of multiprocessing, add tests, and get it merged and released.

**Comment by iandees** [comment]
I can work on it. SOTM US planning has been taking up my time. I'll remove multiprocessing now. What tests did you have in mind?

**Comment by migurski** [comment]
For tests, I want to add something to trigger the multipart upload at a smaller size to ensure it works as-expected.

**Comment by iandees** [comment]
I started on this but ended up mocking out way too much of boto's multipart support, which was very ugly.

**Comment by migurski** [comment]
I think this is in a good place. I’ve added a new test to verify that the correct number of parts exists, refactored the function calls somewhat, made the chunk size a constant, and rebased everything onto `master` to get the tests passing since we switched Circle from Ubuntu 12.04 to 14.04.

**Comment by iandees** [comment]
Awesome, thanks for doing this!

**Pull request merged**
