### PR TITLE
Switch to using esridump library

### PR DESCRIPTION
**Pull request by iandees**

### CODE REVIEW

**Comment by migurski** [comment]
I was thinking about how to test this on my way home. Since the library itself is well-tested, we should mock esridump instead of the underlying HTTP traffic. What do you think?

**Comment by iandees** [comment]
Yep, that makes sense to me.

I'm trying to hack my way through a successful Python GDAL install (the nemesis of every Mac-based geo developer on the planet).

**Comment by iandees** [comment]
…and once I get it installed I can run tests locally and update the tests to mock esridump.

**Comment by migurski** [comment]
I think I used Homebrew to install GDAL on mine, and then pip to specify a matching Python binding? I do this once per computer.

**Comment by iandees** [comment]
I also do it once per computer. And I think I write it down somewhere different each time. Here's the new place I wrote it down:

The Homebrew core gdal is really old (version 1.11 or something), so I `brew install osgeo/osgeo4mac/gdal-20`, which tells you in the Caveats section: 

```
If you need Python to find bindings for this keg-only formula, run:
  echo /usr/local/opt/gdal-20/lib/python2.7/site-packages >> /usr/local/lib/python2.7/site-packages/gdal-20.pth
```

So I put that .pth file in my virtualenv:

```
echo /usr/local/opt/gdal-20/lib/python2.7/site-packages >> ~/.virtualenvs/machine/lib/python2.7/site-packages/gdal-20.pth
```

...and then it worked:

```
(machine) ➜  machine git:(use_esridump_library) ✗ python
Python 2.7.12 (default, Jun 29 2016, 14:05:02)
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from osgeo import ogr
>>>
```

**Comment by migurski** [comment]
…yeah, `virtualenv` with `--no-site-packages`, and then (roughly) `gdal-config --version | xargs -I_ pip install gdal==_`.

**Comment by migurski** [comment]
Yours is good too. I have stuck to version 1.11 for this project by the way; it's more readily-available in PPA form.

**Comment by iandees** [comment]
I think I gdal-20 got installed on my system when I was trying to install qgis via homebrew before, not as a result of this.

**Comment by iandees** [comment]
This has paused briefly because loading the GeoJSON via `ogr.CreateGeometryFromJson(json.dumps(feature))` has revealed that I'm converting some linestrings incorrectly in the pyesridump code. I'm going to fix that and then proceed here.

**Comment by iandees** [comment]
@migurski most of this is done and is probably ready for a review. I think I'll add a couple tests that mock out the calls to esridump tomorrow, but otherwise I'm looking for your thoughts here.

**Comment by iandees** [comment]
This PR is getting pretty big, so it might make sense to merge it and then improve tests in another PR.

**Comment by migurski** [comment]
This is great! Since it removes the `openaddr-esri2geojson` script, it’d be a major version bump. I’m already preparing a 3.x branch for this, with some other deprecated things removed. We could roll it into that branch, or keep a stub `openaddr-esri2geojson` around for 2.x?

**Comment by iandees** [comment]
The most recent commit adds back the `openaddr-esri2geojson` command.

**Comment by migurski** [comment]
👍

**Pull request merged**
