### PR TITLE
Determine objectid field name and use it

### LINKED ISSUE #40: ESRI source fails quietly sometimes
A few of our sources look like they run correctly but produce empty `out.csv` files. In each case it looks like the problem is the ESRI service is not returning any data. Maybe it's a bug in our ESRI scraping code or maybe it's just the service is broken. Either way we should catch this case and signal an error.

At the moment, I think the following sources show the problem:

ca-bc-surrey, us-ak-matanuska_susitna_borough, us-al-calhoun, us-mi-kent, us-mi-ottawa, us-mn-otter_tail, us-nv-las_vegas, us-pa-beaver, us-sc-berkeley, us-sc-lexington, us-sd, us-va-accomack, us-va-city_of_norton, us-va-essex, us-va-fluvanna, us-wi-fond_du_lac, us-wi-vernon, us-wy-laramie

### PR DESCRIPTION
**Pull request by iandees**
Fixes #40.

Some ESRI sources have `objectid` columns that aren't named `objectid`. This queries the metadata for the layer to find the name for the field of type `esriFieldTypeOID` and then uses that when doing the main scrape.

### CODE REVIEW

**Comment by NelsonMinar** [comment]
These changes look great. Thanks for fixing the tests, and thanks for this code in general; I'm pleased to not have to understand the details of ESRI web services :-)

I think it's ready to merge but I'm not going to merge it because Mike's been changing some similar code. Maybe he can merge it, or else I'll sort it out tomorrow.

**Comment by iandees** [comment]
@migurski what do you think of this?

**Comment by NelsonMinar** [comment]
Oh hey thanks for cleaning up the pull request to make it easy to merge. I'm about to press the "Merge pull request" but my Git-fu is weak and I'm not positive it preserves history the way Mike likes. I'll wait a little bit before merging if @migurski doesn't beat me to it.

**Comment by iandees** [comment]
Yep, I'm a bit confused about Mike's preferred git workflow so I want to make sure it's doing what he's looking for.

**Comment by migurski** [comment]
I'm hoping to keep things as-linear-as-possible. Why don’t I try to see if I can rebase these onto `ditch-node`?

**Comment by iandees** [comment]
Ok, sure. At worst just a few cherry-picks.

**Comment by migurski** [comment]
All done: https://github.com/openaddresses/machine/commits/096bd07e5

**Comment by iandees** [comment]
Thanks! I will rebase in the future.

**Pull request closed without merging**
