### PR TITLE
Add dynamic license API response

### PR DESCRIPTION
**Pull request by migurski**
Supports https://github.com/openaddresses/openaddresses-ops/issues/11

Partial sample response:

    {
      "licenses": [
        {
          "attribution": null, "license": null,
          "sources": [
            ["ca/bc/thompson-nicola-regional-district.json", "https://www.tnrd.ca/content/mapping-services-gis-overview"],
            ["ca/bc/vancouver.json", null]
          ]
        },
        {
          "attribution": "ACT Government, Australia", "license": null,
          "sources": [
            ["au/city_of_canberra.json", "http://www.actmapi.act.gov.au/html5.html"]
          ]
        },
        {
          "attribution": null, "license": "Polish Law on Geodesy and Cartography of 17 May 1989 (https://github.com/openaddresses/openaddresses/issues/187#issuecomment-63327973)",
          "sources": [
            ["pl/dolnoslaskie.json", null],
            ["pl/lodzkie.json", null]
          ]
        },
        {
          "attribution": null, "license": "Public Domain",
          "sources": [
            ["us/ca/san_francisco.json", "http://www.sfgov.org"],
            ["us/fl/manatee.json", "http://www.mymanatee.org/home/government/departments/information-technology/gis-home/gis-datadownload.html"]
          ]
        }
      ]
    }

### CODE REVIEW

**Comment by iandees** [comment]
Hmm, the output of this feels "backwards" to me. Wouldn't consumers want to know the mapping between source and license info, not license info and source?

**Comment by NelsonMinar** [comment]
I have the opposite feel from Ian, I like it being sorted by license category. Assuming there's only a few categories. Don't feel strongly though.

**Comment by riordan** [comment]
There's reasons to go either way in terms of organization (or possibly both).

I just want to make sure that when it comes to generating an output from it (e.g. openaddresses/openaddresses.io#67), we display attribution segmented by license. That way users of the main `collected.zip` can point to a single place, while those that opt to add in the 2 share-alike sources can add the additional attribution link.

**Comment by migurski** [comment]
My thinking about organization here is to bundle stuff like all the same-licensed Mexico or Poland sources together, so it’s clearer what the relationship is. OTOH, it would be possible to organize this any which way for output.

**Comment by iandees** [comment]
Maybe it would help for me to understand how you want to display the
information.

**Comment by migurski** [comment]
That’s over in this connected issue: https://github.com/openaddresses/openaddresses.io/pull/67

**Comment by iandees** [comment]
Gotcha. I didn't see the screenshot on my phone earlier. I withdraw my concerns about the API format.

**Comment by migurski** [comment]
:+1: I’m going to deploy this. Thanks!

**Pull request merged**
