### PR TITLE
Add GDB support for sources, take 2

### PR DESCRIPTION
**Pull request by ingalls**
Refs: https://github.com/openaddresses/openaddresses/issues/1720
Refs: https://github.com/openaddresses/openaddresses/pull/1807

### CODE REVIEW

**Comment by ingalls** [comment]
@migurski this is ready to be staged/tested.

**Comment by ingalls** [comment]
A sample json I've been using

```
{
    "coverage": {
        "US Census": {
            "geoid": "06037",
            "name": "Los Angeles County",
            "state": "California"
        },
        "country": "us",
        "state": "ca",
        "county": "Los Angeles"
    },
    "attribution": "Los Angeles County",
    "data": "http://data.openaddresses.io/cache/us-ca-los_angeles.zip",
    "license": "http://egis3.lacounty.gov/dataportal/disclaimer/",
    "year": "",
    "type": "http",
    "compression": "zip",
    "conform": {
        "number": "NUMBER",
        "street": "STRNAME",
        "type": "gdb"
    }
}
```

**Comment by migurski** [comment]
I’ll accept this PR

**Comment by migurski** [comment]
I’m hoping to spend some quality time with this PR.

It looks like the test failures here may be due to a breaking change in WKT precision from GDAL 2, so I’d like to suggest that we upgrade GDAL just enough to get GeoDB support on Trusty, and no further. I guess that would be 1.11? It looks like that is the version [found in ubuntugis-stable](https://launchpad.net/~ubuntugis/+archive/ubuntu/ppa?field.series_filter=trusty), so I wonder whether we can use that. It sounded like you thought it might be appropriate.

The compilation from source is a non-starter for tests, since it takes so long.

**Comment by migurski** [comment]
Thinking it may be possible to get a new-enough version of GDAL by switching the Circle machine from 12.04 to 14.04; testing that in `migurski/machine` to not mess up this fork. Stopping for tonight, to think about the charms of Ruby:

```
(venv-2.7.6) ubuntu@box1678:~/machine$ ruby --version 
ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-linux]

+ gem install chef -v 11.16.4 --no-rdoc --no-ri
ERROR:  Error installing chef:
	rack requires Ruby version >= 2.2.2.
```

**Comment by NelsonMinar** [comment]
> a breaking change in WKT precision from GDAL 2

Are they rounding differently? Would it make sense to adapt our code / tests to work with the new behavior?

**Comment by migurski** [comment]
Yeah, the GDAL 2.x ones are rounding to twelve places while the 1.x ones are rounding to fifteen. I’m hesitant to simply update the tests, because it’ll necessitate updates for anyone working on this code and right now, it seems that 1.11.x is the actual needed version. 

I did a bit of reading, and WKT precision is not a thing that GDAL exposes as a setting.

The use of Ubuntu 14.04 on Circle looks like a possible easy solution, but Ruby/Chef are being uncooperative there.

**Comment by migurski** [comment]
I think I've solved the Ruby/Chef nonsense in #352, and I’m now updating this PR to attempt to run on Ubuntu 14.04, where we should see a working GDAL 1.11 with no manual compilation.

**Comment by migurski** [comment]
Tests are happy, kicking this back over to you @ingalls.

**Comment by ingalls** [comment]
Thanks a ton @migurski really appreciate the time that likely went into this! I'll give it a run as soon as I get in tomorrow, currently on tethered internet.

**Pull request merged**
