### PR TITLE
Give cacher knowledge of the conform object so it can request only the required fields

### LINKED ISSUE #268: Only request necessary fields when Querying Esri Services
An idea, not sure where to implement.

For massive ArcGIS Server-backed services, there may be a significant reduction in response (and processing) time if the request only returned the fields needed for the conform object. Take NY State for example, 4M+ addresses, runs out of time caching.

Here's a request with only the necessary fields + geometry :
http://gisservices.dhses.ny.gov/arcgis/rest/services/SAM_Address_Points/MapServer/1/query?where=1%3D1&text=&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&relationParam=&outFields=CompleteStreetName%2C+AddressNumber&returnGeometry=true&maxAllowableOffset=&geometryPrecision=&outSR=&returnIdsOnly=false&returnCountOnly=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&returnZ=false&returnM=false&gdbVersion=&returnDistinctValues=false&returnTrueCurves=false&resultOffset=&resultRecordCount=&f=pjson

178ms response, 20862 bytes

Here's one with outfields=* (how machine currently runs):
http://gisservices.dhses.ny.gov/arcgis/rest/services/SAM_Address_Points/MapServer/1/query?where=1%3D1&text=&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&relationParam=&outFields=*&returnGeometry=true&maxAllowableOffset=&geometryPrecision=&outSR=&returnIdsOnly=false&returnCountOnly=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&returnZ=false&returnM=false&gdbVersion=&returnDistinctValues=false&returnTrueCurves=false&resultOffset=&resultRecordCount=&f=pjson

299 ms, 75041 byes (almost twice as long and 4x as large).

If the conform object can be loaded before caching to geojson begins, these requests could be made substantially smaller (and the resulting temp files on disk would be smaller too).

### PR DESCRIPTION
**Pull request by iandees**
Fixes #268.

### CODE REVIEW

**Comment by iandees** [comment]
(Looks like Travis is having problems still)

**Comment by migurski** [comment]
I found one python 3 error, but tests now all pass locally for me with 2 and 3.

**Comment by migurski** [comment]
If you think this is ready, I could merge it.

**Comment by iandees** [comment]
I think it's ready to go.

**Pull request merged**
