### PR TITLE
Refactor ESRI downloader to give better errors and fall back to OID enumeration when needed

### PR DESCRIPTION
**Pull request by iandees**

### CODE REVIEW

**Comment by migurski** [comment]
:+1: :+1: :+1: 

What tests can we introduce for this PR? Do we know of sample ESRI endpoints that exhibit new vs. old behavior? Should we be keeping track of ESRI server versions for future reference?

**Comment by iandees** [comment]
Good question. Let me see if I can find one...

**Comment by slibby** [comment]
Here are two that I ran into:
http://data.openaddresses.io.s3.amazonaws.com/runs/34561/output.txt
http://data.openaddresses.io.s3.amazonaws.com/runs/37857/output.txt

**Comment by iandees** [comment]
@slibby I was using this one as a test http://maps.co.palm-beach.fl.us/arcgis/rest/services/Ags/1/MapServer/2

I can't seem to get it to return data with any query method. Do you have any ideas for getting it to work?

**Comment by slibby** [comment]
@iandees looks like that one has no records: http://maps.co.palm-beach.fl.us/arcgis/rest/services/Ags/1/MapServer/2/query?where=1%3D1&returnCountOnly=true&f=pjson

**Comment by iandees** [comment]
Yea, it's a weird one. It reports no records but if you enumerate the object IDs there are several hundred IDs there.

**Comment by iandees** [comment]
@migurski I added a couple tests to cover the fallthrough to enumeration and another one for a weird case I found with the server not respecting the requested field names. :+1:

**Comment by migurski** [comment]
Great! If it’s ready to merge, I can do that.

**Comment by iandees** [comment]
Gooo for it!

**Pull request merged**
