### PR TITLE
Unzip needed files only 

### LINKED ISSUE #87: Unzip only the files that are needed
We are seeing new job timeouts in Poland because machine is pulling all GML files out of a zip archive, even though only one is needed. See http://data.openaddresses.io/runs/1426486295.818/pl-lodzkie.txt.

### PR DESCRIPTION
**Pull request by migurski**
Closes #87.

### CODE REVIEW

**Comment by NelsonMinar** [comment]
Just checking; these new tests don't cause all of the giant pl.zip to be downloaded, do they? A quick read suggests they do but I am probably reading it wrong.

**Comment by migurski** [comment]
The whole zip does get downloaded, as it always has, but the new behavior only extracts the named files. Previously all of the GML content in pl.zip was being extracted and mostly discarded.

**Comment by NelsonMinar** [comment]
No, I mean did you add something to the test suite that now is downloading a big new file? I see now methods like `test_single_pl_l` are using `HTTMock`; perhaps that fakes out the real data?

**Comment by migurski** [comment]
Yeah—it’s download [a small new file](https://github.com/openaddresses/machine/blob/e1d3d850ea745935f5b9e6635c775b05f8415e23/tests/data/pl.zip).

**Pull request merged**
