### PR TITLE
Zip output files

### LINKED ISSUE #56: Serve compressed CSV
Product proposal: we should serve people compressed output files. Unfortunately S3 won't do this for us, in particular it won't do gzip compression in HTTP. There's a bunch of workarounds, I think the best choice for us is to stop serving `out.csv` files and instead serve `out.csv.gz` or maybe `out.zip`. The drawback is it puts the burden on the client to have to manually uncompress the files they download.

dk's out.csv is 130MB. gzipped that's 26MB. (bzip2 is 24MB) us-ca-los_angeles_county goes from 126MB to 33MB. So we're talking about a ~75% space, bandwidth, and time savings.

We could extend this idea to other large products, particularly any `cache.json` or `cache.csv` files.

### PR DESCRIPTION
**Pull request by migurski**
Packages output CSV files into zip archives for faster downloads, and includes [OGR virtual raster](http://www.gdal.org/drv_vrt.html) for ease of opening in geo software.

Closes #56.

### CODE REVIEW

**Comment by NelsonMinar** [comment]
This looks good, nice work!

If we ever wanted to get fancy we could add the extent to the VRT. Also in theory we could be writing the output CSV straight into the ZIP, avoiding the overhead of the extra file and saving disk space on a run. Wouldn't bother with either right now though.

**Comment by iandees** [comment]
Yep, looks great to me!

**Comment by migurski** [comment]
Great, I’ll add a test for the output and merge.

Nelson, extent is a good idea, I’ve added a ticket.

**Comment by migurski** [comment]
VRT is an awful format btw, feeling the need to vent while I wait for Travis tests to run. It looks like XML, but it’s not really XML as I’ve discovered by accidentally putting white space in the wrong places. I think it gets parsed by regular expression? It also fails to have an opinion on file paths, and therefore includes attributes like `relativeToVRT="1"` instead of simply understanding hyperlinks. Also-also, that `"1"` is not a boolean, though booleans are available elsewhere e.g. `reportSrcColumn="FALSE"`.

**Pull request merged**
