### PR TITLE
Use the best paging methods depending on feature support in an ESRI server

### PR DESCRIPTION
**Pull request by iandees**
Previously we used a single method of scraping an ESRI layer. We would retrieve all object IDs for the layer, break them into chunks of ~50 and request those chunks of IDs until we ran out of chunks. This works on most servers, but is extra hard on the server because it's all random access.

After speaking with some ESRI folks they pointed me to [their node.js version of this code](https://github.com/koopjs/featureservice/blob/master/index.js) that uses a couple different mechanisms depending on what the server supports:

1. The fastest and preferred method is to use a server's built-in paging mechanism to page over a query similar to `SELECT * FROM table WHERE 1=1 LIMIT 1000 OFFSET x;`. We don't have to make any extra CPU-consuming requests and can just get started retrieving data in an efficient manner. We can only do this if the server tells us it `supportsPagination`. 
2. The second best method can be used if the server reports `supportsStatistics`. We can use these statistics to get the maximum and minimum value for the layer's object ID (primary key), and then build `WHERE` clauses that page through that key space. This is one extra max/min calculation on top of the first option.
3. The third option is to do what we do now: enumerate all object IDs in a single request and group them into chunks.

A fourth option that I haven't added back in yet is to use spatial queries and make quadtree-like queries. In previous testing, this wasn't faster and in fact probably less efficient (more queries) than the third option above, but sometimes a layer with 100,000s of rows will time out before returning the object ID list, where the quadtree queries would still work.

### CODE REVIEW

**Comment by iandees** [comment]
I'm not seeing why these three tests are failing. Where's the log output go?

**Comment by migurski** [comment]
At the very bottom of the Travis output,

```
======================================================================
FAIL: test_single_car (openaddr.tests.TestOA)
Test complete process_one.process on Carson sample data.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/openaddresses/machine/openaddr/tests/__init__.py", line 228, in test_single_car
    self.assertTrue(state['cache'] is not None)
AssertionError: False is not true
======================================================================
FAIL: test_single_car_cached (openaddr.tests.TestOA)
Test complete process_one.process on Carson sample data.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/openaddresses/machine/openaddr/tests/__init__.py", line 264, in test_single_car_cached
    self.assertTrue(state['cache'] is not None)
AssertionError: False is not true
======================================================================
FAIL: test_single_car_old_cached (openaddr.tests.TestOA)
Test complete process_one.process on Carson sample data.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/openaddresses/machine/openaddr/tests/__init__.py", line 290, in test_single_car_old_cached
    self.assertTrue(state['cache'] is not None)
AssertionError: False is not true
----------------------------------------------------------------------
Ran 134 tests in 61.804s
FAILED (failures=3)
```

**Comment by iandees** [comment]
Yep, I see that, but I don't see any reason for why the cache value has changed. Do the logs from `process_one()` get written out somewhere?

**Comment by iandees** [comment]
Got it! I put some `print()`s in and figured it out.

**Comment by migurski** [comment]
All those logs should be visible behind the "log" links shown throughout results.openaddresses.io. In some rare cases I think timeouts prevent them from coming through. 

If you're using process-one from the command directly for testing, the logs should be right there.

**Comment by iandees** [comment]
Yea I was running tests locally (and in travis) and wasn't seeing them anywhere on the console. There wasn't an obvious logs directory in the directory, either.

**Comment by iandees** [comment]
I updated the description of the PR to include more information about what this change does.

**Comment by migurski** [comment]
Oh yeah, the test runner tries to suppress logging output to make Travis output legible. I usually rely on strategic print() calls when developing tests too, like our Unix forefathers intended.

**Comment by iandees** [comment]
Praise be to stdout. Amen.

**Comment by NelsonMinar** [comment]
The logging system does allow you to show more messages when you're debugging, including per-warning and per-category filtering.

**Comment by migurski** [comment]
Checking in—should this PR get a merge?

**Comment by iandees** [comment]
I should get some more test coverage around this new code. Let me see what I can pull of quickly here tonight.

**Comment by iandees** [comment]
:+1: I think we're good to go.

**Comment by migurski** [comment]
:boom:

**Comment by migurski** [comment]
Rebased and merged in 7d9c097.

**Pull request closed without merging**
