### PR TITLE
Add some fields to the output CSV

### PR DESCRIPTION
**Pull request by iandees**
Include the `city`, `district`, and `region` fields in the output CSV.

### CODE REVIEW

**Comment by NelsonMinar** [comment]
This would close issue #82. I think it makes issue #56 way more urgent; these output files are going to be huge.

**Comment by NelsonMinar** [comment]
Derp, my bad, Mike closed #56 (compressing output) months ago. I'd like to see a size comparison before and after; Ian, do you have a good source to test with?

**Comment by migurski** [comment]
Looks good to me. File compression should take care of the repetitive info in these columns.

**Comment by NelsonMinar** [comment]
This new code doesn't really have any tests associated with it; @iandees could you add a test case for places where city/distrct/region actually get filled?

I tried finding a source file with valid city/region data and failed. `us-ar us-ri us-va us-wa-seattle` all have source parameters but nothing gets emitted to the output. Don't know if the source conform specs are wrong or if the code is buggy.

**Comment by iandees** [comment]
Yea I just noticed that after running us-va. Something's missing.

**Comment by NelsonMinar** [comment]
I tried merging this code with the latest master (after #112) and it seems to be working better. But before we commit this I'd really like some tests to prove we have the fields we expect. @iandees think you can add some?

Sample outputs:

`LON,LAT,NUMBER,STREET,CITY,DISTRICT,REGION,POSTCODE`
`us-ri -71.4854944,41.5444104,101,Cardinal Drive,NORTH KINGSTOWN,,,02852`
`us-va -81.0420562,36.5906893,97,River Place,GALAX,Grayson County,VA,"24,333"`
`us-ar -92.2709769,36.2470493,10493,Highway 5 South,Mountain Home,Baxter,AR,72653`
`us-wa-seattle -122.2723956,47.5448863,4811 F,South Graham Street,,,,`

**Comment by iandees** [comment]
Sure thing. I probably won't get to it today, but maybe tomorrow.

**Comment by migurski** [comment]
I added a few tests, and rebased the whole thing since it was a bit out of date.

**Pull request merged**
