### PR TITLE
[WIP] Add runs table

### LINKED ISSUE #113: Add `runs` table to openaddr.ci
Need a table of runs for each source, to store states over time. Owned and populated by `openaddr.ci` app.

`runs` table contents:

* run id
* source path
    * indexed to quickly see source over time
* blob id
    * indexed to determine repetition; use `git hash-object`
* datetime
* commit id?
    * redundant with datetime?
* state:
    * cache URL
    * cache version (YYYYMMDD?)
    * cache fingerprint MD5 hash
    * cache time elapsed
    * sample URL
    * processed URL
    * process time elapsed
    * log URL

### LINKED ISSUE #116: Introduce ci.worker time limit
I want to introduce a time limit to `openaddr.ci.worker` [near the subprocess call](https://github.com/openaddresses/machine/blob/1.9.2/openaddr/ci/worker.py#L41), to prevent runaway sources and possibly implement queue retries. It should match [`openaddr.ci.jobs.global_job_timeout` if possible](https://github.com/openaddresses/machine/blob/1.9.2/openaddr/jobs.py#L29). @NelsonMinar, you wrote a lot of the job control, how might that work?

### PR DESCRIPTION
**Pull request by migurski**
This set of changes introduces a new `runs` table, used for storing records of individual source runs.

* [x] Implement `ci.pop_task_from_duequeue()`. Don’t implement retries, but do notify Github if a source has failed.
* [x] Add tests for job timeouts, using an artificially short time.
* [x] Add complete JSON source spec to `runs` table for history. Test with malformed input like invalid JSON or UTF8.

Closes #113.
Closes #116.

### CODE REVIEW

**Comment by NelsonMinar** [comment]
This is looking good! I haven't reviewed it closely, but one thought; why not just store the entire source JSON spec in the runs table instead of just `source_path`? That way we have a history in the database.

**Comment by migurski** [comment]
Oh, good thought. I’ll add that.

**Comment by NelsonMinar** [comment]
Cool. Probably best to treat it as TEXT rather than JSON; the user input may not even be well formed.

**Comment by migurski** [comment]
I treated it as raw bytes, since it might not even be valid UTF8 input.

**Pull request merged**
