### PR TITLE
[WIP] Update dotmap

### LINKED ISSUE #210: Update dot map on a schedule
Adapt [@sbma44’s `make_mbtiles.sh` script](https://github.com/openaddresses/openaddresses.io/blob/gh-pages/_src/make_mbtiles.sh) to a set of chef recipes and a thing we can run.

### PR DESCRIPTION
**Pull request by migurski**
* [x] Retrieve all addresses from all current runs.
* [x] Stream addresses to tippecanoe to generate mbtiles.
* [x] Upload mbtiles to Mapbox API.
* [x] Finalize chef recipes to install requirements.
* [x] Figure out how we’ll want to do scheduling.
* [x] Link and document a script.

Closes #210.

### CODE REVIEW

**Comment by migurski** [comment]
Would love your input here @sbma44. I’ve been testing the Mapbox upload process with a tileset called `open-addresses.testing-dotmap`. Before I replace the tileset on OA’s front page, I’d like to figure out how to get a tile image like this generated so we’ll know it’s working end-to-end:

> http://b.tiles.mapbox.com/v4/open-addresses.lg9k5n9i/1/0/0@2x.png
> 
> 0 2x

**Comment by sbma44** [comment]
I think you'll want to use the static maps API for this. 

docs: https://www.mapbox.com/developers/api/static/

Example call using the `open-addresses` account's public access token & the old non-GL style:


https://api.mapbox.com/v4/open-addresses.lg9k5n9i/-77.04,38.89,3/400x300.png?access_token=pk.eyJ1Ijoib3Blbi1hZGRyZXNzZXMiLCJhIjoiSGx0a1B1NCJ9.2O1QelK6jnFXfDznC2pNSw

Unless there's a pressing need for it I'd suggest sticking with the old style. I don't know the current status of the server-side GL static rendering stuff, but I *believe* it's still WIP. Would prefer to let that sleeping dog lie unless we need it (but if we do, I can certainly dig into this).

**Comment by migurski** [comment]
Thanks! If I do that with the tileset ID I’m using for testing, I get a black box:

> `https://api.mapbox.com/v4/open-addresses.testing-dotmap/-77.04,38.89,3/400x300.png?access_token=pk.eyJ1Ijoib3Blbi1hZGRyZXNzZXMiLCJhIjoiSGx0a1B1NCJ9.2O1QelK6jnFXfDznC2pNSw`
> 
> 

What can I do to make it display like the real one?

**Comment by sbma44** [comment]
So the distinction here is between data mapids and style mapids and, worse, GL style mapids.

You're passing in a data mapid, which the static maps API won't accept. The style mapid I provided is currently the only one visible in the open-addresses account. To get this working, we will need to create a new style in Studio Classic that uses your desired data mapid as a source, upload it, and use the new style mapid with the static maps API. From then on when you write new data to the data mapid, the style resources should be refreshed.

I'll be happy to tackle this if you can confirm the mapid you'd like to use for the data.

**Comment by migurski** [comment]
Weird, okay. I replaced `open-addresses.lg9k5n9i` with `open-addresses.testing-dotmap` after confusing it for `open-addresses.lec54np1`. I think `open-addresses.testing-dotmap` is the mapid?

**Comment by sbma44** [comment]
OK, I tried swapping that mapid in. Looks like something's wrong, though. For one thing, there's way too little data there:

image

I can send you account credentials in Slack if you want to stop playing telephone, but I'm happy to continue working to figure this out if you'd rather not have to dig into Mapbox mysteries.

**Comment by migurski** [comment]
Yep—this is using data _only_ from a small test set. I want to see some dots before I start hitting it with the full 200m / 1.6GB. 11MB sounds like what I remember!

**Comment by sbma44** [comment]
ohhhhhhh. sorry. missed that part. ok, here's the new style mapid: `open-addresses.68b62b86`

static API example:


https://api.mapbox.com/v4/open-addresses.68b62b86/55.5,-21.15,9/400x300.png?access_token=pk.eyJ1Ijoib3Blbi1hZGRyZXNzZXMiLCJhIjoiSGx0a1B1NCJ9.2O1QelK6jnFXfDznC2pNSw

**Comment by migurski** [comment]
Looks good, thanks! So, when I push a fresh version of tileset `open-addresses.testing-dotmap `, the new dots should always appear at map `open-addresses.68b62b86 `?

**Comment by sbma44** [comment]
Yup, exactly right (allowing for rebuilding time, which should be pretty quick)

**Comment by migurski** [comment]
:boom: Mexico City, showing a successful upload:

**Comment by migurski** [comment]
My kingdom for labels-on-top.

**Comment by sbma44** [comment]
@migurski a) nice! b) I tried to take a look at this without success. It's certainly easy in GL :-/

if you'll be using these renders elsewhere lmk, this is a solvable problem, I'm just not the guy to solve it

**Pull request merged**
