### PR TITLE
ESRI -> .lower() -> esri

### PR DESCRIPTION
**Pull request by slibby**

### CODE REVIEW

**Comment by NelsonMinar** [comment]
Would you mind adding a test for the new behavior? I believe there are tests for the old already, but I'm not sure.

**Comment by slibby** [comment]
@NelsonMinar sure, I'll try to add a test or two that reflect this.

**Comment by migurski** [comment]
Hey @slibby, just checking in to see if you’re thinking about tests for this!

**Comment by slibby** [comment]
@migurski Would love some guidance on where to insert that / a test to base it on?

**Comment by migurski** [comment]
Sure, I’d probably start here: https://github.com/openaddresses/machine/blob/d617273ef024828b8369f465dfa90494ee937704/openaddr/tests/conform.py#L529

There are a bunch of tests right around that code which check `find_source_path()`, the function edited in this PR.

**Pull request closed without merging**
