### PR TITLE
Only attempt to write out the cached columns in ESRI downloader

### PR DESCRIPTION
**Pull request by iandees**

### CODE REVIEW

**Comment by iandees** [comment]
@migurski, is there a test for the caching output?

**Comment by migurski** [comment]
I don’t believe there is—I’ll look later on, might be tomorrow before I can work on adding one.

**Comment by iandees** [comment]
Where are your priorities, @migurski? It's only Christmas day. :smile:

**Comment by migurski** [comment]
Tests pass with Pythons 2 and 3, and I’ve rebased onto master. I sure wish Travis would fix their shit. Okay to merge?

**Comment by iandees** [comment]
Why avoid the literal asterisk? The asterisk is analogous to `SELECT *`.

Either way it looks good, OK to merge! Thanks

**Comment by migurski** [comment]
I wanted to differentiate the results of that method a little, and move the magic `*` string nearer to the query context where it’s meaningful. Is that okay?

**Comment by iandees** [comment]
Yep, that makes sense. :+1:

**Pull request merged**
