### PR TITLE
OpenAddresses V2 Schema

### PR DESCRIPTION
**Pull request by ingalls**
Add support for the V2 OpenAddresses Schema to machine while retaining backwards computability with V1 

## Approach

To Be Written

_V2 Schema Discussion_
Ref: https://github.com/openaddresses/openaddresses-ops/issues/21

_DC V2 Schema Branch_
Ref: https://github.com/openaddresses/openaddresses/pull/3923

cc/ @openaddresses/machinists

### CODE REVIEW

**Comment by ingalls** [comment]
Sample Source File I've been using for tests:

```JSON
{
    "schema": 2,
    "coverage": {
        "country": "us", "state": "dc" },
    "layers": {
        "addresses": [{
            "name": "open-data",
            "type": "http",
            "data": "https://s3.amazonaws.com/data.openaddresses.io/cache/uploads/v2_test/Address_Points.zip",
            "compression": "zip",
            "conform": {
                "type": "geojson",
                "number": { "function": "prefixed_number", "field": "address" },
                "street": { "function": "postfixed_street", "field": "address" },
                "city": "city",
                "region": "state",
                "postcode": "postalcode"
            }
        },{
            "name": "sheriff",
            "type": "http",
            "data": "https://s3.amazonaws.com/data.openaddresses.io/cache/uploads/v2_test/Address_Points.zip",
            "compression": "zip",
            "conform": {
                "type": "geojson",
                "number": { "function": "prefixed_number", "field": "address" },
                "street": { "function": "postfixed_street", "field": "address" },
                "city": "city",
                "region": "state",
                "postcode": "postalcode"
            }
        },{
            "name": "ng-e911",
            "type": "http",
            "data": "https://s3.amazonaws.com/data.openaddresses.io/cache/uploads/v2_test/Address_Points.zip",
            "compression": "zip",
            "conform": {
                "type": "geojson",
                "number": { "function": "prefixed_number", "field": "address" },
                "street": { "function": "postfixed_street", "field": "address" },
                "city": "city",
                "region": "state",
                "postcode": "postalcode"
            }
        }],
        "buildings": [{
            "name": "open-data",
            "type": "http",
            "data": "https://s3.amazonaws.com/data.openaddresses.io/cache/uploads/v2_test/Building_Footprints.zip",
            "compression": "zip",
            "conform": {
                "type": "geojson"
            }

        }],
        "parcels": [{
            "name": "open-data",
            "type": "http",
            "data": "https://s3.amazonaws.com/data.openaddresses.io/cache/uploads/v2_test/Parcel_Lots.zip",
            "compression": "zip",
            "conform": {
                "type": "geojson"
            }

        }]
    }
}

```

**Comment by migurski** [comment]
Could we skip the formatting commits for the time being? They make it hard to see what changes are actually happening.

**Comment by ingalls** [comment]
@migurski Fied, my vim setup turns these a very obnoxious red, I've disabled for now, ignoring muscle memory is hard :P

**Comment by migurski** [comment]
Thanks! I’m in favor of making these changes and setting up an editorconfig for this.

**Comment by migurski** [comment]
@ingalls, here are some answers to the questions you asked this morning when we talked.

Messages:
- Job tasks are [added to the queue in `ci. add_files_to_queue`](https://github.com/openaddresses/machine/blob/25d3ae77404f38273fef360e1cebb20953c57f18/openaddr/ci/__init__.py#L760-L777), called [from `ci.create_queued_job`](https://github.com/openaddresses/machine/blob/25d3ae77404f38273fef360e1cebb20953c57f18/openaddr/ci/__init__.py#L743-L758). One job can have multiple tasks, [as in this recent example](http://results.openaddresses.io/jobs/f49cfa12-6835-4f4c-9b8c-b0c8237fef92).
- Jobs are [read from the queue in `ci. pop_task_from_taskqueue`](https://github.com/openaddresses/machine/blob/25d3ae77404f38273fef360e1cebb20953c57f18/openaddr/ci/__init__.py#L927-L1002), called [from `ci.worker.main`](https://github.com/openaddresses/machine/blob/25d3ae77404f38273fef360e1cebb20953c57f18/openaddr/ci/worker.py#L52-L70). That’s called [via `openaddr-ci-worker `](https://github.com/openaddresses/machine/blob/25d3ae77404f38273fef360e1cebb20953c57f18/setup.py#L22).

For the latest successful run on a source, [probably `ci.objects.read_latest_run`](https://github.com/openaddresses/machine/blob/25d3ae77404f38273fef360e1cebb20953c57f18/openaddr/ci/objects.py#L554-L582) is the most relevant function. We store successful and unsuccessful runs in the DB all together, and show the successful ones on the front page. For example, `mx/agu/statewide` [broke a few weeks ago](http://results.openaddresses.io/sources/mx/agu/statewide) and we [show that failure on the latest set](https://results.openaddresses.io/sets/376269/), but we still [make an effort to show available data on the front page](http://results.openaddresses.io/?runs=all#runs).

**Comment by migurski** [comment]
Also, in case you’re poking around in the database, you’ll see that [there are four named queues](https://github.com/openaddresses/machine/blob/master/docs/persistence.md#queue).

**Comment by ingalls** [comment]
## Tracking

Heading out, things to pickup once I get back

### Errors

- The last error is in regards to a webhook
- Line num:144 of `openaddr/ci/work.py` is the culprit

```
  File "/usr/local/src/openaddr/openaddr/ci/work.py", line 147, in do_work
    with open(state_fullpath) as file:
FileNotFoundError: [Errno 2] No such file or directory: ''
```

### Next Steps

- As can be seen from the above error, the next step is to update all of the consumers of process_one output to expect a list
- Ensure the CLI interface of process_one returns a JSON dumped List

**Comment by ingalls** [comment]
Per voice, going to take a different approach at this now that https://github.com/openaddresses/machine/pull/693 has landed.

**Pull request closed without merging**
