### PR TITLE
Always query all fields in ESRI

### LINKED ISSUE #332: Request all fields for ESRI sources
We seem to run into a bunch of problems with ESRI endpoints when we request specific fields, so I think we should undo the specific field requests that I added in #269 to solve #268.

These are the sorts of errors we get from this: http://s3.amazonaws.com/data.openaddresses.io/runs/87479/output.txt

### PR DESCRIPTION
**Pull request by iandees**
Fixes #332.

Sort of reverts #269.

### CODE REVIEW

**Comment by iandees** [comment]
I'm trying to get machine running tests locally but running in to all sorts of problems since upgrading to El Capitan. Damnit Apple...

**Comment by iandees** [comment]
Since my existing Google searches turned up blank, here's what I ran into and the solution I cam up with.

`pip install gdal` was trying to install gdal 2.1.0 and homebrew was installing gdal 1.11, so I was getting this stack of errors because of a missing header:

```
Installing collected packages: gdal
  Running setup.py install for gdal ... error
    Complete output from command /Users/iandees/.virtualenvs/machine/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/0r/jc0r8qys1lj7fx8vgtgc0z580000gn/T/pip-build-cp_96K/gdal/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/0r/jc0r8qys1lj7fx8vgtgc0z580000gn/T/pip-fzp_fX-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/iandees/.virtualenvs/machine/include/site/python2.7/gdal:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.11-intel-2.7
    copying gdal.py -> build/lib.macosx-10.11-intel-2.7
    copying ogr.py -> build/lib.macosx-10.11-intel-2.7
    copying osr.py -> build/lib.macosx-10.11-intel-2.7
    copying gdalconst.py -> build/lib.macosx-10.11-intel-2.7
    creating build/lib.macosx-10.11-intel-2.7/osgeo
    copying osgeo/__init__.py -> build/lib.macosx-10.11-intel-2.7/osgeo
    copying osgeo/gdal.py -> build/lib.macosx-10.11-intel-2.7/osgeo
    copying osgeo/gdal_array.py -> build/lib.macosx-10.11-intel-2.7/osgeo
    copying osgeo/gdalconst.py -> build/lib.macosx-10.11-intel-2.7/osgeo
    copying osgeo/gdalnumeric.py -> build/lib.macosx-10.11-intel-2.7/osgeo
    copying osgeo/gnm.py -> build/lib.macosx-10.11-intel-2.7/osgeo
    copying osgeo/ogr.py -> build/lib.macosx-10.11-intel-2.7/osgeo
    copying osgeo/osr.py -> build/lib.macosx-10.11-intel-2.7/osgeo
    running build_ext
    building 'osgeo._gdal' extension
    creating build/temp.macosx-10.11-intel-2.7
    creating build/temp.macosx-10.11-intel-2.7/extensions
    cc -fno-strict-aliasing -fno-common -dynamic -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -Wno-error=unused-command-line-argument-hard-error-in-future -pipe -Wno-error=unused-command-line-argument-hard-error-in-future -I../../port -I../../gcore -I../../alg -I../../ogr/ -I../../ogr/ogrsf_frmts -I../../gnm -I../../apps -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I. -I/usr/local/Cellar/gdal/1.11.3_1/include -c extensions/gdal_wrap.cpp -o build/temp.macosx-10.11-intel-2.7/extensions/gdal_wrap.o
    warning: unknown warning option '-Werror=unused-command-line-argument-hard-error-in-future'; did you mean '-Werror=unused-command-line-argument'? [-Wunknown-warning-option]
    warning: unknown warning option '-Werror=unused-command-line-argument-hard-error-in-future'; did you mean '-Werror=unused-command-line-argument'? [-Wunknown-warning-option]
    extensions/gdal_wrap.cpp:3089:10: fatal error: 'cpl_vsi_error.h' file not found
    #include "cpl_vsi_error.h"
             ^
    2 warnings and 1 error generated.
    error: command 'cc' failed with exit status 1

    ----------------------------------------
Command "/Users/iandees/.virtualenvs/machine/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/0r/jc0r8qys1lj7fx8vgtgc0z580000gn/T/pip-build-cp_96K/gdal/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/0r/jc0r8qys1lj7fx8vgtgc0z580000gn/T/pip-fzp_fX-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/iandees/.virtualenvs/machine/include/site/python2.7/gdal" failed with error code 1 in /private/var/folders/0r/jc0r8qys1lj7fx8vgtgc0z580000gn/T/pip-build-cp_96K/gdal/
```

Instead of running `pip install gdal`, I used `pip install gdal==1.11.0` to match the version that homebrew installed and it worked. 👍

**Comment by migurski** [comment]
Sorry about this! I install this on Mac OS X approximately once per laptop, so it’s not a well tested or documented process. I’d like to get access to a clean, recent machine and document an install from scratch.

**Comment by iandees** [comment]
It's not your fault, it's a confluence of homebrew, Apple, and OSGEO all having inconsistent installation procedures.

**Comment by migurski** [comment]
About e4a92b4, I recall pinning the requests version because of this issue: https://bugs.launchpad.net/ubuntu/+source/python-pip/+bug/1306991/comments/10

Do we need the newer requests, or can we stick with this older pinned version?

**Comment by migurski** [comment]
Since we've moved this code, can we move this issue as well?

**Comment by iandees** [comment]
Yep!

**Comment by iandees** [comment]
I can't believe it was only June when I ran into the problem of installing gdal.

**Comment by migurski** [comment]
I think my recent suggestion to specify a GDAL version with pip was based on your less-recent suggestion to specify a GDAL version with pip.

**Pull request closed without merging**
