### PR TITLE
street array as merge [WIP]

### PR DESCRIPTION
**Pull request by ingalls**
At the moment we have several internal machine functions whose output is forced upon the user.

The one I run into the most is the merge function. The user is forced to relate `merge: ['',''] => street: 'auto_street'`. 

This PR changes this behavior merging arrays automatically. 

so `{ merge: {'PRE','STR'}, street: 'auto_street'} `.  becomes `{ street: ['PRE','STR'] }`

### CODE REVIEW

**Comment by sbma44** [comment]
looks good to me -- the auto_street stuff is pretty confusing. I think there *might* be one or two sources that use `advanced_merge` on `auto_street` but I'm not 100% on that.

**Comment by NelsonMinar** [comment]
I think this change is a good one and should be committed as-is. Thanks for updating all the tests!

A bunch of source files will need to be updated in openaddresses. That will then break the Node code; are we no longer worried about compatibility for it?

To @sbma44's point about `advanced_merge` on `auto_street` I took a quick look and I think only the `kr-seoul-*` sources do that. They all do though. I'd feel better if those were tested by hand and a unit test for their use-case was added to the test suite.

As you've implemented it only `street` has the special array behavior. It strikes me this could be extended to any field we synthesize, and possibly replace `advanced_merge`. Although that has special behavior for `separator` we need to preserve.

**Comment by ingalls** [comment]
@NelsonMinar I have a proposal I'm finishing up that will address the advanced merge functionality, allowing`[]` concating on all fields (we currently don't capture partial numbers as they are usually a separate field) and deprecating `split` for something better. 

I'll have a document to review and then a subsequent PR in the coming days. 

In the meantime I'll create a PR against OA/openaddresses that removes the `merge` fields and puts them in `street`.

**Comment by ingalls** [comment]
I've made a PR against the main repo here: https://github.com/openaddresses/openaddresses/pull/1143

**Comment by migurski** [comment]
Piping in with some notes from our offline conversation: I’d like to update this PR to support both old and new behavior, and I believe I can do that this weekend.

**Comment by ingalls** [comment]
Backtracking to reintroduce the old behavior results in a really messy diff. Going to close this and cherry-pick this into a new PR.

**Pull request closed without merging**
