### PR TITLE
Lowercase "field_to_remove" value in in conform_smash_case

### PR DESCRIPTION
**Pull request by thatdatabaseguy**
See: https://github.com/openaddresses/openaddresses/pull/2301

### CODE REVIEW

**Comment by iandees** [comment]
Would it make more sense to remove case smashing altogether?

**Comment by thatdatabaseguy** [comment]
Sure. Wasn't going to make architecture changes in a PR :-), but as long as it doesn't break any source, it should be fine.

**Comment by iandees** [comment]
It might break some sources but I'd rather have the sources match case. Not sure why - it just feels like the right thing to do 🙂. @migurski do you have an opinion?

**Comment by NelsonMinar** [comment]
I've always hated case smashing; the only reason I wrote it was to match the old Node code's behavior. It adds a surprising amount of complication.

**Comment by migurski** [comment]
I don't have a strong opinion about this. As long tests pass and they stay representative of the real data we work with, then removing case smashing would be fine by me.

**Pull request merged**
