### PR TITLE
accounting for the chain function in EsriRestDownloadTask.field_names_to_request

### PR DESCRIPTION
**Pull request by albarrentine**
In attempting to test the new `chain` function, I realized that one other change to machine is required for it all to work. The reason for the  [failed](https://s3.amazonaws.com/data.openaddresses.io/runs/226280/output.txt) build in https://github.com/openaddresses/openaddresses/pull/3203 is in `EsriRestDownloadTask.field_names_to_request`. This method assumes each conform function has a property named either "fields" or "field", which does not apply to the compound `chain` function.

This change collects fields from the chain's constituent functions.

### CODE REVIEW

**Comment by migurski** [comment]
Looks good! Can we get a unit test added for this change?

**Comment by thatdatabaseguy** [comment]
added a test though unclear why no build is running.

**Comment by migurski** [comment]
Whoa, weird.

**Comment by migurski** [comment]
I'm unsure why Circle isn't building. I've turned it off an on again, and I'll need to try jiggling it with a new commit to see if it works.

**Comment by migurski** [comment]
Well this is frustrating. Sorry the tests have somehow stopped — I'll keep digging when I have a free moment, to figure out what’s happening.

**Comment by thatdatabaseguy** [comment]
In any case I've tested the change locally and it looks fine.

**Comment by iandees** [comment]
Closing in favor of #764.

**Pull request closed without merging**
