### PR TITLE
Fixing awscli/botocore dependency

### PR DESCRIPTION
**Pull request by migurski**
Seeing some weirdness and conflicts between apt-gotten `awscli` and pip-installed `awscli`.

### CODE REVIEW

**Comment by jalessio** [comment]
@migurski I was seeing some boto version errors too (I think?) on a fresh install. Are these related to this fix?
```
pkg_resources.VersionConflict: (botocore 1.4.80 (/usr/local/lib/python3.4/dist-packages), Requirement.parse('botocore==1.4.79'))
```
and
```
pkg_resources.DistributionNotFound: botocore==1.4.79
```

These are pulled from full log at https://gist.github.com/jalessio/07081407c3c5acebbb65e2ae660dc120

**Comment by migurski** [comment]
Yes, I think. Try running from this branch maybe to see if they clear up? 

This is all part of me getting some of the log results schlepped off to S3.

**Comment by jalessio** [comment]
👍  No instances of the string "boto" in test output after running clean install on this branch

https://gist.github.com/jalessio/7288a86e11c3c1c0dc04a8310dba1911

**Comment by migurski** [comment]
Hurrah!

**Pull request merged**
