### PR TITLE
Add Docker support

### PR DESCRIPTION
**Pull request by MiniCodeMonkey**
This adds docker support to `machine`, allowing you to easily run a local copy without having to worry about dependencies.

My use case is being able to test changes to conform files directly on my Mac before PR'ing them.

Let me know if you guys think it would be useful to a broader audience or if you have any questions/suggestions for this.

### CODE REVIEW

**Comment by migurski** [comment]
Neat! Any way you might modify the Dockerfile slightly to use the chef scripts? This new version has some duplication in it that feels like it could fall out of synch, since Docker isn’t a tool I use with any regularity while working.

**Comment by MiniCodeMonkey** [comment]
Hey,

I see the issue with duplication, unfortunately there's not really any good way to use Chef with Docker currently -- it would greatly complicate things and would be against best practices.

I would argue that having this duplication could be considered acceptable due to the above and due to the fact that it's very minimal.

What do you think?

Mathias

**Comment by migurski** [comment]
Can you say more about the best practices?

**Comment by geobrando** [comment]
https://www.chef.io/solutions/containers/

https://supermarket.chef.io/cookbooks/docker

**Comment by migurski** [comment]
I think I might be asking the opposite question: not how to manage containers with Chef, but how to use existing Chef cookbooks within a container.

**Comment by geobrando** [comment]
@migurski Ahh.  Didn't really read the links, but thought they may have some useful info.  Makes sense though

**Comment by davidchiles** [comment]
I'm a novice to docker and have no experience with chef... so ... I tried some things.

I tried using the existing chef script from the Dockerfile and it failed at a step where it was tring to setup some database.

After fumbling around I got this to work https://github.com/davidchiles/machine/commit/131a157ce18a36f2f393afa7e26182ead94cd438

I'm able to run `openaddr-process-one` but not able to render a preview.

Just some breadcrumbs for anyone else trying this out.

**Comment by migurski** [comment]
We have some more complete Docker work in https://github.com/openaddresses/machine/pull/587, so I'm going to close this PR. @MiniCodeMonkey, thank you for your help! I know it’s taken a while, but we’re finally in a place where Docker is something we can support fully.

**Pull request closed without merging**
